from __future__ import annotations


KPI_CATALOG = [
    {
        "id": "bi-kpi-001",
        "code": "total_remittances",
        "name": "Remesas",
        "description": "Cantidad de remesas dentro del periodo y filtros seleccionados.",
        "category": "NEGOCIO",
        "formula": "count(transactions)",
        "unit": "count",
        "source": "transactions",
        "aggregation": "count",
        "filters_supported": ["date_from", "date_to", "origin_country", "destination_country", "currency", "status"],
        "interpretation": "Mide actividad transaccional.",
        "limitations": "Incluye todos los estados filtrados; no implica remesas completadas.",
    },
    {
        "id": "bi-kpi-002",
        "code": "total_amount_usd_equivalent",
        "name": "Monto movilizado",
        "description": "Suma del monto origen convertido a USD equivalente.",
        "category": "NEGOCIO",
        "formula": "sum(source_amount * exchange_rate_to_usd[source_currency])",
        "unit": "USD equivalente",
        "source": "transactions, app.analytics.constants.EXCHANGE_RATES_TO_USD",
        "aggregation": "sum",
        "filters_supported": ["date_from", "date_to", "origin_country", "destination_country", "currency", "status"],
        "interpretation": "Permite comparar volumen monetario multimeda en una unidad comun.",
        "limitations": "Usa tasas configurables/sinteticas, no historicas oficiales.",
    },
    {
        "id": "bi-kpi-003",
        "code": "average_ticket_usd_equivalent",
        "name": "Ticket promedio",
        "description": "Monto movilizado promedio por remesa.",
        "category": "TRANSACCIONES",
        "formula": "total_amount_usd_equivalent / total_remittances",
        "unit": "USD equivalente",
        "source": "transactions",
        "aggregation": "ratio",
        "filters_supported": ["date_from", "date_to", "origin_country", "destination_country", "currency", "status"],
        "interpretation": "Resume el tamano promedio de remesa.",
        "limitations": "Puede distorsionarse por outliers.",
    },
    {
        "id": "bi-kpi-004",
        "code": "total_commission_revenue_usd_equivalent",
        "name": "Ingresos por comision",
        "description": "Suma de comisiones historicas almacenadas convertidas a USD equivalente.",
        "category": "INGRESOS",
        "formula": "sum(commission_amount * exchange_rate_to_usd[source_currency])",
        "unit": "USD equivalente",
        "source": "transactions.commission_amount",
        "aggregation": "sum",
        "filters_supported": ["date_from", "date_to", "origin_country", "destination_country", "currency", "status"],
        "interpretation": "Aproxima ingresos brutos por comision.",
        "limitations": "No representa utilidad neta ni costos operativos.",
    },
    {
        "id": "bi-kpi-005",
        "code": "average_commission_usd_equivalent",
        "name": "Comision promedio",
        "description": "Ingreso promedio por comision por remesa.",
        "category": "INGRESOS",
        "formula": "total_commission_revenue_usd_equivalent / total_remittances",
        "unit": "USD equivalente",
        "source": "transactions.commission_amount",
        "aggregation": "ratio",
        "filters_supported": ["date_from", "date_to", "origin_country", "destination_country", "currency", "status"],
        "interpretation": "Mide monetizacion promedio por transaccion.",
        "limitations": "Depende de valores historicos almacenados.",
    },
    {
        "id": "bi-kpi-006",
        "code": "active_clients",
        "name": "Clientes activos",
        "description": "Clientes remitentes con al menos una remesa en el periodo.",
        "category": "CLIENTES",
        "formula": "count_distinct(sender_id)",
        "unit": "count",
        "source": "transactions.sender_id",
        "aggregation": "distinct count",
        "filters_supported": ["date_from", "date_to", "origin_country", "destination_country", "currency", "status"],
        "interpretation": "Mide usuarios con actividad transaccional.",
        "limitations": "No expone PII ni mide clientes receptores.",
    },
    {
        "id": "bi-kpi-007",
        "code": "active_corridors",
        "name": "Corredores activos",
        "description": "Cantidad de pares origen-destino con actividad.",
        "category": "CORREDORES",
        "formula": "count_distinct(origin_country, destination_country)",
        "unit": "count",
        "source": "transactions",
        "aggregation": "distinct count",
        "filters_supported": ["date_from", "date_to", "origin_country", "destination_country", "currency", "status"],
        "interpretation": "Mide diversidad geografica de actividad.",
        "limitations": "Corredor geografico no implica nivel de riesgo.",
    },
    {
        "id": "bi-kpi-008",
        "code": "completion_rate",
        "name": "Tasa de finalizacion",
        "description": "Remesas completadas sobre remesas elegibles.",
        "category": "OPERACIONES",
        "formula": "count(status=COMPLETED) / count(status in eligible_statuses)",
        "unit": "ratio",
        "source": "transactions.status",
        "aggregation": "ratio",
        "filters_supported": ["date_from", "date_to", "origin_country", "destination_country", "currency", "status"],
        "interpretation": "Mide proporcion de remesas completadas.",
        "limitations": "Estados abiertos reducen la tasa sin implicar falla definitiva.",
    },
]


def get_kpi_catalog() -> list[dict]:
    return KPI_CATALOG
