BLOCKCHAIN_ENGINE_VERSION = "local-blockchain-v1"
HASH_ALGORITHM = "SHA-256"
DEFAULT_DIFFICULTY = 2
GENESIS_PREVIOUS_HASH = "0" * 64
GENESIS_EVENT_TYPE = "GENESIS"
GENESIS_ENTITY_TYPE = "BLOCKCHAIN"
GENESIS_ENTITY_REFERENCE = "FIDUCIA-GENESIS"
GENESIS_SCHEMA_VERSION = "blockchain-genesis-v1"
LEGACY_REMITTANCE_EVIDENCE_SCHEMA = "remittance-evidence-v1"
REMITTANCE_EVIDENCE_SCHEMA = "remittance-evidence-v2"
RISK_EVIDENCE_SCHEMA = "risk-evidence-v1"
SUPPORTED_SCHEMA_VERSIONS = {GENESIS_SCHEMA_VERSION, LEGACY_REMITTANCE_EVIDENCE_SCHEMA, REMITTANCE_EVIDENCE_SCHEMA, RISK_EVIDENCE_SCHEMA}

BLOCKCHAIN_EVENTS = {
    "REMITTANCE_CREATED",
    "RISK_ASSESSMENT_RECORDED",
    "REMITTANCE_AVAILABLE",
    "REMITTANCE_COMPLETED",
}
